print("p1", require("src/p1").problem())
print("p2", require("src/p2").problem())
print("p3", require("src/p3").problem())
print("p4", require("src/p4").problem())
print("p5", require("src/p5").problem())
print("p6", require("src/p6").problem())
