default: run-all

run-all:
    @./lua src/main.lua

run NUM:
    @./lua -e 'local succeded, _ = pcall(function() local p = require("src/p{{NUM}}");print(p.problem());end); if succeded == false then print("errored") end'

list-problems:
    @ls src | grep 'p[0-9]*\.lua' | awk -F '.' '{print $1}' | sort -h

new NUM:
    @echo "local function main()\n\t-- TODO\n\treturn 0\nend\nreturn {\n\tproblem = main,\n}"> src/p{{NUM}}.lua
    @echo "print(\"p{{NUM}}\", require(\"src/p{{NUM}}\").problem())" >> src/main.lua
    @sort src/main.lua | uniq > src/main.lua2 && mv src/main.lua2 src/main.lua
